services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: true

  # PSR Controllers
  Pheature\Crud\Psr7\Toggle\GetFeatures:
    class: Pheature\Crud\Psr7\Toggle\GetFeatures
    arguments:
      - '@Pheature\Core\Toggle\Read\FeatureFinder'
      - '@Psr\Http\Message\ResponseFactoryInterface'
    tags: [ 'controller.service_arguments' ]

  Pheature\Crud\Psr7\Toggle\GetFeature:
    class: Pheature\Crud\Psr7\Toggle\GetFeature
    arguments:
      - '@Pheature\Core\Toggle\Read\FeatureFinder'
      - '@Psr\Http\Message\ResponseFactoryInterface'
    tags: [ 'controller.service_arguments' ]

  Pheature\Crud\Psr7\Toggle\PostFeature:
    class: Pheature\Crud\Psr7\Toggle\PostFeature
    arguments:
      - '@Pheature\Crud\Toggle\Handler\CreateFeature'
      - '@Psr\Http\Message\ResponseFactoryInterface'
    tags: [ 'controller.service_arguments' ]

  Pheature\Crud\Psr7\Toggle\PatchFeature:
    class: Pheature\Crud\Psr7\Toggle\PatchFeature
    arguments:
      - '@Pheature\Crud\Toggle\Handler\AddStrategy'
      - '@Pheature\Crud\Toggle\Handler\RemoveStrategy'
      - '@Pheature\Crud\Toggle\Handler\EnableFeature'
      - '@Pheature\Crud\Toggle\Handler\DisableFeature'
      - '@Psr\Http\Message\ResponseFactoryInterface'
    tags: [ 'controller.service_arguments' ]

  Pheature\Crud\Psr7\Toggle\DeleteFeature:
    class: Pheature\Crud\Psr7\Toggle\DeleteFeature
    arguments:
      - '@Pheature\Crud\Toggle\Handler\RemoveFeature'
      - '@Psr\Http\Message\ResponseFactoryInterface'
    tags: [ 'controller.service_arguments' ]
