services:
  _defaults:
    autowire: false
    autoconfigure: false

  Pheature\Crud\Toggle\Handler\CreateFeature:
    class: Pheature\Crud\Toggle\Handler\CreateFeature
    arguments:
      - '@Pheature\Core\Toggle\Write\FeatureRepository'

  Pheature\Crud\Toggle\Handler\SetStrategy:
    class: Pheature\Crud\Toggle\Handler\SetStrategy
    arguments:
      - '@Pheature\Core\Toggle\Write\FeatureRepository'

  Pheature\Crud\Toggle\Handler\RemoveStrategy:
    class: Pheature\Crud\Toggle\Handler\RemoveStrategy
    arguments:
      - '@Pheature\Core\Toggle\Write\FeatureRepository'

  Pheature\Crud\Toggle\Handler\EnableFeature:
    class: Pheature\Crud\Toggle\Handler\EnableFeature
    arguments:
      - '@Pheature\Core\Toggle\Write\FeatureRepository'

  Pheature\Crud\Toggle\Handler\DisableFeature:
    class: Pheature\Crud\Toggle\Handler\DisableFeature
    arguments:
      - '@Pheature\Core\Toggle\Write\FeatureRepository'

  Pheature\Crud\Toggle\Handler\RemoveFeature:
    class: Pheature\Crud\Toggle\Handler\RemoveFeature
    arguments:
      - '@Pheature\Core\Toggle\Write\FeatureRepository'
