pheature_flags_toggle_detail:
  methods: [GET]
  path: /features/{feature_id}
  controller: Pheature\Crud\Psr7\Toggle\GetFeature::handle

pheature_flags_feature_list:
  methods: [GET]
  path: /features
  controller: Pheature\Crud\Psr7\Toggle\GetFeatures::handle

pheature_flags_feature_create:
  methods: [POST]
  path: /features/{feature_id}
  controller: Pheature\Crud\Psr7\Toggle\PostFeature::handle

pheature_flags_feature_update:
  methods: [PATCH]
  path: /features/{feature_id}
  controller: Pheature\Crud\Psr7\Toggle\PatchFeature::handle

pheature_flags_feature_remove:
  methods: [DELETE]
  path: /features/{feature_id}
  controller: Pheature\Crud\Psr7\Toggle\DeleteFeature::handle
