name: generate_changelog

on:
  workflow_run:
    workflows:
      - "split_monorepo0"
    types:
      - completed

jobs:
  generate_changelog:
    name: "Generate Changelog"
    runs-on: ubuntu-latest

    steps:
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        name: "Checkout"
        uses: "actions/checkout@v2"

      -
        if: "startsWith(github.ref, 'refs/tags/')"
        name: "Write Changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.CHANGELOG_TOKEN }}
          user: pheature-flags
          project: pheature-flags
          output: ./CHANGELOG.md
          maxIssues: 9999999
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          unreleased: true
          filterByMilestone: false
          compareLink: true
          author: true
          usernamesAsGithubLogins: true

      -
        if: "startsWith(github.ref, 'refs/tags/')"
        name: "Commit changes"
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default:
          default_author: github_actor

          # The name of the user that will be displayed as the author of the commit
          # Default: depends on the default_author input
          author_name: ${{ github.event.pusher.name }}

          # The email of the user that will be displayed as the author of the commit
          # Default: depends on the default_author input
          author_email: ${{ github.event.pusher.email }}

          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'update changelog'

          # The flag used on the pull strategy. Use NO-PULL to avoid the action pulling at all.
          # Default: '--no-rebase'
          pull_strategy: '--no-rebase'

          branch: 1.0.x

          # Whether to use the --signoff option on `git commit` (only `true` and `false` are accepted)
          # Default: false
          signoff: true

          push: --force-with-lease
